## Welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,76,7]] , np.int64)

In [3]:
myarr

array([[ 3,  6, 76,  7]])

In [4]:
myarr[0, 1]

np.int64(6)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0, 1] = 45 ## 6 ki jgh 45 ho jaayega

In [7]:
myarr

array([[ 3, 45, 76,  7]])

## Array creation : Conversion from other Python structures

In [8]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int64')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,43,54})

array({34, 43, 54}, dtype=object)

## Intrinsic NumPy array creation functions

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,50,10) ## 1 to 50 10 number

In [19]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 8.01097889e-307, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 9.34611148e-307],
       [1.37961709e-306, 1.42418172e-306, 1.37961641e-306,
        9.45699679e-308, 2.22522596e-306, 8.34424341e-308]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
ide = np.identity(15)

In [25]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [26]:
arr = np.arange(99)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
arr = arr.reshape(3,33)

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr = arr.ravel()

In [31]:
arr.shape

(99,)

## Axis in numpy (IN 2D ARRAY :- axis 0 = rows, axis 1=columns ) 

In [32]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [33]:
ar = np.array(x)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
ar.sum(axis=0) ## sum of all columns

array([12, 15, 18])

In [36]:
ar.sum(axis=1) ## sum of all rows

array([ 6, 15, 24])

In [37]:
ar.T ## tanspose kr dega matrix ko

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
ar.flat

In [39]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [41]:
ar.size

9

In [42]:
ar.nbytes

72

In [43]:
one = np.array([1,3,4,65,5])

In [44]:
one.argmax() ## give me max index number

np.int64(3)

In [45]:
one.argmin()

np.int64(0)

In [46]:
one.argsort() ## number of indices for sorting

array([0, 1, 2, 4, 3])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
ar.argmin()

np.int64(0)

In [49]:
ar.argmax()

np.int64(8)

In [50]:
ar.argmax(axis=0) ## isme hr ek column me jis bhi index pr value bdii h vo hi likha aayega like (7,8,9) indices will be (2,2,2)

array([2, 2, 2])

In [51]:
ar.argmin(axis=1) ## isme hr ek row me jis bhi index pr value small h vo hi likha aayega like (1,4,7) indices will be (0,0,0)

array([0, 0, 0])

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [55]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [56]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [57]:
ar.sum()

np.int64(45)

In [58]:
ar.max()

np.int64(9)

In [59]:
ar.min()

np.int64(1)

In [60]:
# how to element find in array

In [61]:
np.where(ar<3)

(array([0, 0]), array([0, 1]))

In [62]:
type(np.where(ar>3))

tuple

In [63]:
import sys

In [64]:
py_ar = [0,4,55,2]

In [65]:
np_ar = np.array(py_ar)

In [66]:
sys.getsizeof(1) * len(py_ar)

112

In [67]:
np_ar.itemsize * np_ar.size

32

In [68]:
np_ar.tolist()

[0, 4, 55, 2]